export const specialities = [
    {value: 1, label: 'Acupuntura'},
    {value: 2, label: 'Alergia e Imunologia'},
    {value: 3, label: 'Anestesiologia'},
    {value: 4, label: 'Medicina Legal e Perícia Médica'},
    {value: 5, label: 'Medicina Nuclear'},
    {value: 6, label: 'Reumatologia'},
    {value: 7, label: 'Urologia'},
    {value: 8, label: 'Áreas de Atuação reconhecidas'},
    {value: 9, label: 'Administração em Saúde'},
    {value: 10, label: 'Ecografia Vascular com Doppler'},
    {value: 11, label: 'Eletrofisiologia Clínica Invasiva'},
    {value: 12, label: 'Psiquiatria da Infância e Adolescência'},
    {value: 13, label: 'Psiquiatria Forense'},
    {value: 14, label: 'Radiologia Intervencionista e Angiorradiologia'},
    {value: 15, label: 'Reumatologia Pediátrica'},
    {value: 16, label: 'Sexologia'},
    {value: 17, label: 'Transplante de Medula Óssea'},
    {value: 18, label: 'Ultrassonografia em Ginecologia e Obstetrícia'}
]
