@url = http://46b8-2804-431-c7e8-97e4-200e-45ec-b8b2-41e9.ngrok.io/mais-consulta 

### Home (Medico)
GET {{url}}/medico/{doctorId}/agendamentos HTTP/1.1


### Home (Medico)
GET {{url}}/agendamento/pegar/horas HTTP/1.1

# Retorno esperado
# [
    # {
        # id: number, (esse e o id do paciente)
        # name: string,
        # age: number,
        # scheduleTime: time
    # }
# ]

### Pacientes (Medico)
GET {{url}}/medico/historico HTTP/1.1
# Tela que condiz com o historico de pacientes atendidos por esse medico
# Retorno esperado
# [
    # {
        # name: string,
        # age: number,
        # lastAppointment: string
    # }
# ]
###

POST {{url}}/auth/signin HTTP/1.1
content-type: application/json

{
    "cpf": "36014447806",
    "password": "123"
}